apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: dev
spec:
  selector:
    app: docker-registry-ui
  type: NodePort
  ports:
  - port: 80
    nodePort: 30008
---
apiVersion: apps/v1 # Which version of the Kubernetes API you're using to create this object
kind: Deployment # What kind of object you want to create
metadata:
  name: docker-registry-ui
  namespace: dev
spec: # What state you desire for the object
  selector:
    matchLabels:
      app: docker-registry-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      containers:
      - name: docker-registry-ui
        image: joxit/docker-registry-ui:main
        ports:
          - containerPort: 80
        env:
        - name: SINGLE_REGISTRY
          value: "true"
        - name: REGISTRY_TITLE
          value: "Docker Registry UI"
        - name: DELETE_IMAGES
          value: "true"
        - name: SHOW_CONTENT_DIGEST
          value: "true"
        - name: NGINX_PROXY_PASS_URL
          value: "http://192.168.2.221:30005"
        - name: SHOW_CATALOG_NB_TAGS
          value: "true"
        - name: CATALOG_MIN_BRANCHES
          value: "1"
        - name: CATALOG_MAX_BRANCHES
          value: "1"
        - name: TAGLIST_PAGE_SIZE
          value: "100"
        - name: REGISTRY_SECURED
          value: "false"
        - name: CATALOG_ELEMENTS_LIMIT
          value: "1000"
