# 报错：chown: /var/lib/postgresql/data/postgresql.conf: Read-only file system
# 原因：From kubernetes 1.8 on, configmap is mounted readonly by default.
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test
  name: pg-config-slave # 主从节点都配置同样的内容
data:
  postgresql.conf: | # | 符号被称为折叠标记，表示下方缩进的区块中包含多行文本数据
    wal_level = replica
    max_wal_senders = 10
    wal_sender_timeout = 60s
    max_slot_wal_keep_size = 1GB
    hot_standby = on