apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-registry-sc
  namespace: dev
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer # 延迟 PVC 绑定，直到 pod 被调度
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # PVC 被删除后，PV 的留存策略
  storageClassName: docker-registry-sc
  local: # 表示 pv 使用本地存储
    path: /data/docker-registry
  # 使用 local pv 需要定义 nodeAffinity，k8s 需要根据 nodeAffinity 将 Pod 调度到有对应 local volume 的 node 上
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - server3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: dev
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: docker-registry-sc
  resources:
    requests:
      storage: 10Gi # 声明存储的大小
  volumeName: docker-registry-pv # 绑定 PV
