apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: dev
spec:
  selector:
    app: docker-registry
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30005
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
  namespace: dev
spec:
  selector:
    matchLabels:
      app: docker-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-pvc
              mountPath: /var/lib/registry
            - name: registry-config
              mountPath: /etc/docker/registry/config.yml
              subPath: config.yml
      volumes:
        - name: registry-pvc
          persistentVolumeClaim:
            claimName: docker-registry-pvc
        - name: registry-config
          configMap:
            name: docker-registry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry
  namespace: dev
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
      delete:
        enabled: true
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
