apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: dev
spec:
  selector:
    app: gitlab
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080
    - name: ssh
      port: 22
      nodePort: 30022
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: dev
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: 192.168.2.221:30005/gitlab-ce:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 22
          env:
            - name: shm-size
              value: "256m"
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-pvc
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-pvc
          persistentVolumeClaim:
            claimName: gitlab-pvc
        - name: gitlab-config
          hostPath:
            path: /data/gitlab/config
        - name: gitlab-logs
          hostPath:
            path: /data/gitlab/logs
