# 用于备份数据的 pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backup-pv
  namespace: test
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # PVC 被删除后，PV 的留存策略
  storageClassName: mysql-sc
  local: # 表示 pv 使用本地存储
    path: /mnt/disks/vol2
  # 使用 local pv 需要定义 nodeAffinity，k8s 需要根据 nodeAffinity 将 Pod 调度到有对应 local volume 的 node 上
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubt-srv-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mysql-sc
  resources:
    requests:
      storage: 1Gi # 声明存储的大小
  volumeName: mysql-backup-pv # 绑定 PV