apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: test
spec:
  selector:
    app: mysql
  clusterIP: None
  ports:
    - port: 3306
---
apiVersion: apps/v1 # Which version of the Kubernetes API you're using to create this object
kind: StatefulSet # What kind of object you want to create
metadata: # Data that helps uniquely identify the object, including a name string, UID, and optional namespace
  name: mysql
  namespace: test
spec: # What state you desire for the object
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  template: # 创建副本的时候按照模板内描述的内容来创建
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          volumeMounts:
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-cm
              mountPath: /etc/my.cnf.d/my.cnf
              subPath: my.cnf
      volumes:
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-cm
          configMap:
            name: mysql-config